### ISSUE TITLE
\chordmode vs. \figuremode

### ISSUE THREAD

**Issue by th-we** [rettinghaus/MEILER#13]
What should be the logic for distinguishing what `<harm>` elements belong to `\chordmode` and which ones belong to `\figuremode`?

I think the guidelines and sample set are quite clear that for figured bass, `<fb>` markup inside `<harm>` should be used. Therefore I'd use `\figuremode` for everything with `<fb>` and `\chordmode` on everything else.

It has to be kept in mind that both `\chordmode` and `\figuremode` might be required in parallel.

**Comment by rettinghaus** [comment]
I left it out, because `<harm>` for itself is totally unstructured (unlike in MusicXML). So there is no straight way to convert those to lilypond's `\chordmode`. 
Instead for converting `<harm>` without `<fb>` we should use given `@startid` and treat it as simple `\markup` (similar to `<dir>`). 

For a more structured approach in MEI you should open a bug over there.
